# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    exception:
        enabled: true
        exception_controller: 'App\Controller\Api\ExceptionController::showAction'
#        codes:
#            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
#            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
    body_listener:
        array_normalizer: fos_rest.normalizer.camel_keys
    param_fetcher_listener:  true
    allowed_methods_listener:  true
    routing_loader: true
    view:
        view_response_listener:  true
    format_listener:
        enabled:              false
        service:              null
        rules:
            - { path: ^/, prefer_extension: false, fallback_format: json, priorities: [ json ] }
