framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: ~

    templating:
        engines: ['twig']

    php_errors:
        log: true

#    cache:
#    serializer:
#        name_converter: 'serializer.name_converter.camel_case_to_snake_case'

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    service:
        mailer: app.custom_fos_user_mailer
    from_email:
        address: '%env(MAILER_USER_ADDRESS)%'
        sender_name: '%env(MAILER_USER_NAME)%'
    registration:
        form:
            type: App\Form\RegistrationType
        confirmation:
            enabled: true
    profile:
        form:
            type: App\Form\ProfileType