security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

        refresh_token_user_provider:
            id: security.refresh_token_user_provider

        jwt_user_provider:
            id: security.jwt_user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|docs)/
            security: false

        api_login:
            pattern:  ^/login$
            stateless: true
            provider: jwt_user_provider
            gfreeau_get_jwt:
                username_parameter: username
                password_parameter: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api_refresh_token:
            pattern: ^/refresh_token$
            stateless: true
            provider: refresh_token_user_provider
            simple_preauth:
                authenticator: security.refresh_token_authenticator

        api_registration:
            pattern: ^/register
            stateless: true
            anonymous: true

        api_password_reset:
            pattern: ^/password/reset
            stateless: true
            anonymous: true

        api_account_exists:
            pattern: ^/accounts$
            stateless: true
            anonymous: true

        app_docs:
            pattern: ^/docs$
            stateless: true
            anonymous: true

        api:
            pattern: ^/
            stateless: true
            provider: jwt_user_provider
            lexik_jwt:
                authorization_header:
                    enabled: true
                    prefix:  Bearer
                throw_exceptions:        true
                create_entry_point:      true
                authentication_provider: lexik_jwt_authentication.security.authentication.provider

    access_control:
        - { path: ^/accounts$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/docs, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/password/reset, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,       roles: IS_AUTHENTICATED_FULLY }
