source 'https://rubygems.org' do
  gem "capistrano", "~> 3.10"
  gem 'capistrano-symfony', '~> 1.0.0.rc3'
  gem 'capistrano-file-permissions'
  gem 'capistrano-npm'
  gem 'capistrano-touch-linked-files'
  gem 'capistrano-bundler', '~> 1.3'
  gem 'capistrano-rvm'
end